# Generated by Django 4.2.7 on 2025-02-16 08:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('date', models.TimeField(verbose_name='Время')),
                ('image', models.ImageField(upload_to='managers_img/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Фио')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='Фио')),
                ('full_name_ky', models.CharField(max_length=255, null=True, verbose_name='Фио')),
                ('job_title', models.CharField(max_length=255, verbose_name='Должность')),
                ('job_title_ru', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('job_title_ky', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='managers_img/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('date', models.TimeField(verbose_name='Время')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('full_name_ru', models.CharField(max_length=100, null=True, verbose_name='ФИО')),
                ('full_name_ky', models.CharField(max_length=100, null=True, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'график приема ггражда',
            },
        ),
        migrations.CreateModel(
            name='Structure_admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Структура администрации')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Структура администрации')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Структура администрации')),
                ('image', models.ImageField(upload_to='managers_img/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Структура администрации',
                'verbose_name_plural': 'Структуры администрации',
            },
        ),
    ]
