# Generated by Django 4.2.7 on 2025-02-17 09:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_catalog_description_ky_catalog_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'график приема гражданы', 'verbose_name_plural': 'график приема гражданы'},
        ),
        migrations.AddField(
            model_name='catalog',
            name='description_detail',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание детально'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='date',
            field=models.CharField(max_length=155, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.CharField(max_length=155, verbose_name='Время'),
        ),
    ]
