# Generated by Django 4.2.7 on 2025-02-18 10:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_catalog_description_detail_ky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталогдор'},
        ),
        migrations.AlterModelOptions(
            name='managers',
            options={'verbose_name': 'Жетекчи', 'verbose_name_plural': 'Жетекчилер'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Жарандарды кабыл алуу графиги', 'verbose_name_plural': 'Жарандарды кабыл алуу графиги'},
        ),
        migrations.AlterModelOptions(
            name='structure_admins',
            options={'verbose_name': 'Администрациянын түзүмү', 'verbose_name_plural': 'Администрациянын түзүмдөрү'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='date',
            field=models.CharField(max_length=155, verbose_name='Убактысы'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description_detail',
            field=ckeditor.fields.RichTextField(verbose_name='Толук сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description_detail_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Толук сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description_detail_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Толук сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(upload_to='managers_img/', verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Толук аты-жөнү'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='full_name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Толук аты-жөнү'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Толук аты-жөнү'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='image',
            field=models.ImageField(upload_to='managers_img/', verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='job_title',
            field=models.CharField(max_length=255, verbose_name='Кызматы'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='job_title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Кызматы'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='job_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Кызматы'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.CharField(max_length=155, verbose_name='Убактысы'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Толук аты-жөнү'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='full_name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Толук аты-жөнү'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='full_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Толук аты-жөнү'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Темасы'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Темасы'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Темасы'),
        ),
        migrations.AlterField(
            model_name='structure_admins',
            name='image',
            field=models.ImageField(upload_to='managers_img/', verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='structure_admins',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Администрациянын түзүмү'),
        ),
        migrations.AlterField(
            model_name='structure_admins',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Администрациянын түзүмү'),
        ),
        migrations.AlterField(
            model_name='structure_admins',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Администрациянын түзүмү'),
        ),
    ]
