# Generated by Django 4.2.7 on 2025-02-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='we_invite_to_view',
            name='date_place',
            field=models.CharField(max_length=155, verbose_name='Дата места просмотра'),
        ),
    ]
