# Generated by Django 4.2.7 on 2025-02-18 10:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_latestnews_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннер'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='latestnews',
            options={'verbose_name': 'Акыркы жаңылыктар', 'verbose_name_plural': 'Акыркы жаңылыктар'},
        ),
        migrations.AlterModelOptions(
            name='we_invite_to_view',
            options={'verbose_name': 'Биз көрүүгө сунуштайбыз', 'verbose_name_plural': 'Биз көрүүгө сунуштайбыз'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Толук аты-жөнү'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='full_name_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Толук аты-жөнү'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='full_name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Толук аты-жөнү'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner_images/', verbose_name='Баннердин сүрөтү'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Баннердин аталышы'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Баннердин аталышы'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Баннердин аталышы'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(upload_to='base/', verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_gallery',
            field=models.CharField(max_length=255, verbose_name='Галереянын аталышы'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_gallery_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Галереянын аталышы'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_gallery_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Галереянын аталышы'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='image',
            field=models.ImageField(upload_to='latest_news_images/', verbose_name='Жаңылыктын сүрөтү'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Жаңылыктын аталышы'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Жаңылыктын аталышы'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Жаңылыктын аталышы'),
        ),
        migrations.AlterField(
            model_name='we_invite_to_view',
            name='date_place',
            field=models.CharField(max_length=155, verbose_name='Көрүү жайынын датасы'),
        ),
        migrations.AlterField(
            model_name='we_invite_to_view',
            name='description_place',
            field=models.CharField(max_length=255, verbose_name='Көрүү жайынын сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='we_invite_to_view',
            name='description_place_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Көрүү жайынын сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='we_invite_to_view',
            name='description_place_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Көрүү жайынын сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='we_invite_to_view',
            name='image_place',
            field=models.ImageField(upload_to='base/', verbose_name='Көрүү жайынын сүрөтү'),
        ),
        migrations.AlterField(
            model_name='we_invite_to_view',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Биз көрүүгө сунуштайбыз'),
        ),
        migrations.AlterField(
            model_name='we_invite_to_view',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Биз көрүүгө сунуштайбыз'),
        ),
        migrations.AlterField(
            model_name='we_invite_to_view',
            name='title_place',
            field=models.CharField(max_length=255, verbose_name='Көрүү жайынын аталышы'),
        ),
        migrations.AlterField(
            model_name='we_invite_to_view',
            name='title_place_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Көрүү жайынын аталышы'),
        ),
        migrations.AlterField(
            model_name='we_invite_to_view',
            name='title_place_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Көрүү жайынын аталышы'),
        ),
        migrations.AlterField(
            model_name='we_invite_to_view',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Биз көрүүгө сунуштайбыз'),
        ),
    ]
