# Generated by Django 4.2.7 on 2025-02-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_banner_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='settings', verbose_name='лого')),
                ('title_logo', models.CharField(max_length=155, verbose_name='Заголовка Логотипа')),
                ('title_logo_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовка Логотипа')),
                ('title_logo_ky', models.CharField(max_length=155, null=True, verbose_name='Заголовка Логотипа')),
                ('location', models.CharField(max_length=155, verbose_name='Локация')),
                ('location_ru', models.CharField(max_length=155, null=True, verbose_name='Локация')),
                ('location_ky', models.CharField(max_length=155, null=True, verbose_name='Локация')),
                ('phone', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('link_phone', models.URLField(verbose_name='Ссылки на номер телефона')),
                ('link_insta', models.URLField(verbose_name='Ссылки на интсраграм')),
                ('link_telegram', models.URLField(verbose_name='Ссылки на телеграм')),
                ('link_watapp', models.URLField(verbose_name='Ссылки на ватсап')),
                ('link_youtube', models.URLField(verbose_name='Ссылки на ютуб')),
                ('link_facebook', models.URLField(verbose_name='Ссылки на файсбук')),
                ('end_news', models.CharField(max_length=155, verbose_name='Последний новости')),
                ('end_news_ru', models.CharField(max_length=155, null=True, verbose_name='Последний новости')),
                ('end_news_ky', models.CharField(max_length=155, null=True, verbose_name='Последний новости')),
                ('preview', models.CharField(max_length=155, verbose_name='Предосмотр')),
                ('preview_ru', models.CharField(max_length=155, null=True, verbose_name='Предосмотр')),
                ('preview_ky', models.CharField(max_length=155, null=True, verbose_name='Предосмотр')),
                ('gallery', models.CharField(max_length=155, verbose_name='Галлерия')),
                ('gallery_ru', models.CharField(max_length=155, null=True, verbose_name='Галлерия')),
                ('gallery_ky', models.CharField(max_length=155, null=True, verbose_name='Галлерия')),
                ('news_nookat', models.CharField(max_length=155, verbose_name='Носовти о Ноокат')),
                ('news_nookat_ru', models.CharField(max_length=155, null=True, verbose_name='Носовти о Ноокат')),
                ('news_nookat_ky', models.CharField(max_length=155, null=True, verbose_name='Носовти о Ноокат')),
                ('title_cmi', models.CharField(max_length=155, verbose_name='СМИ')),
                ('title_cmi_ru', models.CharField(max_length=155, null=True, verbose_name='СМИ')),
                ('title_cmi_ky', models.CharField(max_length=155, null=True, verbose_name='СМИ')),
                ('project_title', models.CharField(max_length=155, verbose_name='Проекты')),
                ('project_title_ru', models.CharField(max_length=155, null=True, verbose_name='Проекты')),
                ('project_title_ky', models.CharField(max_length=155, null=True, verbose_name='Проекты')),
            ],
            options={
                'verbose_name_plural': 'Главная настройка',
            },
        ),
    ]
