# Generated by Django 4.2.7 on 2025-02-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_settings_title_admin_settings_title_admin_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='anti_corup',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Антикорупций'),
        ),
        migrations.AddField(
            model_name='settings',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовка Локация'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_news',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Последний новости'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_news_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Последний новости'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_news_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Последний новости'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='gallery',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Галлерия'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='gallery_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Галлерия'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='gallery_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Галлерия'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='news_nookat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Носовти о Ноокат'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='news_nookat_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Носовти о Ноокат'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='news_nookat_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Носовти о Ноокат'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='preview',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Предосмотр'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='preview_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Предосмотр'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='preview_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Предосмотр'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='project_title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='project_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_admin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовка Авминитсратора'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_admin_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовка Авминитсратора'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_admin_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовка Авминитсратора'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_cmi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='СМИ'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_cmi_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='СМИ'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_cmi_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='СМИ'),
        ),
    ]
