# Generated by Django 4.2.7 on 2025-02-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_settings_anti_corup_settings_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='anti_corup_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Антикорупций'),
        ),
        migrations.AddField(
            model_name='settings',
            name='anti_corup_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Антикорупций'),
        ),
        migrations.AddField(
            model_name='settings',
            name='location_name_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовка Локация'),
        ),
        migrations.AddField(
            model_name='settings',
            name='location_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовка Локация'),
        ),
    ]
