# Generated by Django 4.2.7 on 2025-02-17 11:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoMini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Заголовок')),
                ('title_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовок')),
                ('title_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='photo_kg/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
