# Generated by Django 4.2.7 on 2025-02-18 10:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photomini'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryarchivalphotos',
            options={'verbose_name': 'Тарыхый сүрөттөр', 'verbose_name_plural': 'Тарыхый сүрөттөр'},
        ),
        migrations.AlterModelOptions(
            name='gallerynewshapes',
            options={'verbose_name': 'Жаңы сүрөттөр', 'verbose_name_plural': 'Жаңы сүрөттөр'},
        ),
        migrations.AlterModelOptions(
            name='galleryoshtour',
            options={'verbose_name': '3D Тур', 'verbose_name_plural': '3D Тур'},
        ),
        migrations.AlterModelOptions(
            name='photomini',
            options={'verbose_name_plural': 'Өнөктөштөр'},
        ),
        migrations.AddField(
            model_name='photomini',
            name='link',
            field=models.URLField(default=1, verbose_name='шилтеме'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryarchivalphotos',
            name='image',
            field=models.ImageField(upload_to='gallery_photos/', verbose_name='Архивдик сүрөт'),
        ),
        migrations.AlterField(
            model_name='galleryarchivalphotos',
            name='image_ky',
            field=models.ImageField(null=True, upload_to='gallery_photos/', verbose_name='Архивдик сүрөт'),
        ),
        migrations.AlterField(
            model_name='galleryarchivalphotos',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='gallery_photos/', verbose_name='Архивдик сүрөт'),
        ),
        migrations.AlterField(
            model_name='gallerynewshapes',
            name='image',
            field=models.ImageField(upload_to='gallery_photos/', verbose_name='Жаңы фигуралардын сүрөтү'),
        ),
        migrations.AlterField(
            model_name='gallerynewshapes',
            name='image_ky',
            field=models.ImageField(null=True, upload_to='gallery_photos/', verbose_name='Жаңы фигуралардын сүрөтү'),
        ),
        migrations.AlterField(
            model_name='gallerynewshapes',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='gallery_photos/', verbose_name='Жаңы фигуралардын сүрөтү'),
        ),
        migrations.AlterField(
            model_name='galleryoshtour',
            name='image',
            field=models.ImageField(upload_to='gallery_images/', verbose_name='Ош Турдун сүрөтү'),
        ),
        migrations.AlterField(
            model_name='galleryoshtour',
            name='image_ky',
            field=models.ImageField(null=True, upload_to='gallery_images/', verbose_name='Ош Турдун сүрөтү'),
        ),
        migrations.AlterField(
            model_name='galleryoshtour',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='gallery_images/', verbose_name='Ош Турдун сүрөтү'),
        ),
        migrations.AlterField(
            model_name='galleryoshtour',
            name='link',
            field=models.URLField(verbose_name='Шилтеме'),
        ),
        migrations.AlterField(
            model_name='galleryoshtour',
            name='link_ky',
            field=models.URLField(null=True, verbose_name='Шилтеме'),
        ),
        migrations.AlterField(
            model_name='galleryoshtour',
            name='link_ru',
            field=models.URLField(null=True, verbose_name='Шилтеме'),
        ),
        migrations.AlterField(
            model_name='galleryoshtour',
            name='title',
            field=models.CharField(max_length=135, verbose_name='Ош Турдун аталышы'),
        ),
        migrations.AlterField(
            model_name='galleryoshtour',
            name='title_ky',
            field=models.CharField(max_length=135, null=True, verbose_name='Ош Турдун аталышы'),
        ),
        migrations.AlterField(
            model_name='galleryoshtour',
            name='title_ru',
            field=models.CharField(max_length=135, null=True, verbose_name='Ош Турдун аталышы'),
        ),
        migrations.AlterField(
            model_name='photomini',
            name='image',
            field=models.ImageField(upload_to='photo_kg/', verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='photomini',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='photomini',
            name='title_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='photomini',
            name='title_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Аталышы'),
        ),
    ]
