# Generated by Django 4.2.7 on 2025-02-16 10:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutNok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('description_ky', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(upload_to='about-nok/')),
            ],
            options={
                'verbose_name': 'О Нокатской область',
                'verbose_name_plural': 'О Нокатской область',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_media', models.CharField(max_length=100, verbose_name='Заголовок СМИ страницы "Новости"')),
                ('title_media_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок СМИ страницы "Новости"')),
                ('title_media_ky', models.CharField(max_length=100, null=True, verbose_name='Заголовок СМИ страницы "Новости"')),
                ('description_media', ckeditor.fields.RichTextField(verbose_name='Описание СМИ страницы "Новости"')),
                ('description_media_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание СМИ страницы "Новости"')),
                ('description_media_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание СМИ страницы "Новости"')),
                ('date_media', models.DateTimeField(verbose_name='Дата СМИ страницы "Новости"')),
                ('image_media', models.ImageField(upload_to='news/')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'СМИ',
                'verbose_name_plural': 'СМИ',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('title_ru', models.TextField(null=True, verbose_name='Заголовок')),
                ('title_ky', models.TextField(null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='news/')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('first_paragraph', ckeditor.fields.RichTextField(verbose_name='Первый абзац')),
                ('first_paragraph_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Первый абзац')),
                ('first_paragraph_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Первый абзац')),
                ('second_paragraph', ckeditor.fields.RichTextField(verbose_name='Второй абзац')),
                ('second_paragraph_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Второй абзац')),
                ('second_paragraph_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Второй абзац')),
                ('general_paragraph', ckeditor.fields.RichTextField(verbose_name='Общий абзац')),
                ('general_paragraph_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Общий абзац')),
                ('general_paragraph_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Общий абзац')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsNok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField()),
                ('title_ru', ckeditor.fields.RichTextField(null=True)),
                ('title_ky', ckeditor.fields.RichTextField(null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('description_ky', ckeditor.fields.RichTextField(null=True)),
                ('date', models.CharField(max_length=225)),
                ('date_ru', models.CharField(max_length=225, null=True)),
                ('date_ky', models.CharField(max_length=225, null=True)),
                ('photo', models.ImageField(upload_to='news-nok/')),
            ],
            options={
                'verbose_name': 'Новость Нокатская область',
                'verbose_name_plural': 'Новости Нокатская область',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='project_images/', verbose_name='Фото')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_detail', ckeditor.fields.RichTextField(verbose_name='Описание детально')),
                ('description_detail_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание детально')),
                ('description_detail_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание детально')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='TourismNok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField()),
                ('title_ru', ckeditor.fields.RichTextField(null=True)),
                ('title_ky', ckeditor.fields.RichTextField(null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('description_ky', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(upload_to='tourism-nok/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
