# Generated by Django 4.2.7 on 2025-02-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Дата'),
        ),
    ]
