# Generated by Django 4.2.7 on 2025-02-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='date_media',
            field=models.CharField(max_length=155, verbose_name='Дата СМИ страницы "Новости"'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=155, verbose_name='Дата'),
        ),
    ]
