# Generated by Django 4.2.7 on 2025-02-18 10:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_media_date_media_alter_news_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutnok',
            options={'verbose_name': 'Нок району жөнүндө', 'verbose_name_plural': 'Нок району жөнүндө'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'ЖМК', 'verbose_name_plural': 'ЖМК'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Жаңылыктар', 'verbose_name_plural': 'Жаңылыктар'},
        ),
        migrations.AlterModelOptions(
            name='newsnok',
            options={'verbose_name': 'Нок районунун жаңылыгы', 'verbose_name_plural': 'Нок районунун жаңылыктары'},
        ),
        migrations.AlterModelOptions(
            name='newsobject',
            options={'verbose_name': 'Сүрөттөр', 'verbose_name_plural': 'Сүрөттөр'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Долбоор', 'verbose_name_plural': 'Долбоорлор'},
        ),
        migrations.AlterField(
            model_name='aboutnok',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='aboutnok',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='aboutnok',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='aboutnok',
            name='image',
            field=models.ImageField(upload_to='about-nok/', verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='media',
            name='date_media',
            field=models.CharField(max_length=155, verbose_name='ЖМК бетинин датасы'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description_media',
            field=ckeditor.fields.RichTextField(verbose_name='ЖМК бетинин сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description_media_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='ЖМК бетинин сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description_media_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='ЖМК бетинин сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='media',
            name='link',
            field=models.URLField(verbose_name='Шилтеме'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title_media',
            field=models.CharField(max_length=100, verbose_name='ЖМК бетинин аталышы'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title_media_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='ЖМК бетинин аталышы'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title_media_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='ЖМК бетинин аталышы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='news',
            name='first_paragraph',
            field=ckeditor.fields.RichTextField(verbose_name='Биринчи абзац'),
        ),
        migrations.AlterField(
            model_name='news',
            name='first_paragraph_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Биринчи абзац'),
        ),
        migrations.AlterField(
            model_name='news',
            name='first_paragraph_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Биринчи абзац'),
        ),
        migrations.AlterField(
            model_name='news',
            name='general_paragraph',
            field=ckeditor.fields.RichTextField(verbose_name='Жалпы абзац'),
        ),
        migrations.AlterField(
            model_name='news',
            name='general_paragraph_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Жалпы абзац'),
        ),
        migrations.AlterField(
            model_name='news',
            name='general_paragraph_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Жалпы абзац'),
        ),
        migrations.AlterField(
            model_name='news',
            name='second_paragraph',
            field=ckeditor.fields.RichTextField(verbose_name='Экинчи абзац'),
        ),
        migrations.AlterField(
            model_name='news',
            name='second_paragraph_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Экинчи абзац'),
        ),
        migrations.AlterField(
            model_name='news',
            name='second_paragraph_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Экинчи абзац'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ky',
            field=models.TextField(null=True, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='newsnok',
            name='date',
            field=models.CharField(max_length=225, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='newsnok',
            name='date_ky',
            field=models.CharField(max_length=225, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='newsnok',
            name='date_ru',
            field=models.CharField(max_length=225, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='newsnok',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='newsnok',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='newsnok',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='newsnok',
            name='photo',
            field=models.ImageField(upload_to='news-nok/', verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='newsnok',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='newsnok',
            name='title_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='newsnok',
            name='title_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='newsobject',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='Жаңылык'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_detail',
            field=ckeditor.fields.RichTextField(verbose_name='Толук сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_detail_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Толук сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_detail_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Толук сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project_images/', verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='tourismnok',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='tourismnok',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='tourismnok',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='tourismnok',
            name='image',
            field=models.ImageField(upload_to='tourism-nok/', verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='tourismnok',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='tourismnok',
            name='title_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='tourismnok',
            name='title_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Аталышы'),
        ),
    ]
