# Generated by Django 4.2.7 on 2025-02-17 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.CreateModel(
            name='InfoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.info', verbose_name='информацию')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Фотография информаций',
            },
        ),
    ]
