# Generated by Django 4.2.7 on 2025-02-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_alter_info_image_infoobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeinformation',
            options={'verbose_name_plural': 'Тип Информаций'},
        ),
        migrations.CreateModel(
            name='GeneralInformationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('general_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='passport.generalinformation')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
