# Generated by Django 4.2.7 on 2025-02-17 12:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0003_alter_typeinformation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=155, verbose_name="Тип Информаций"),
                ),
                ("img", models.ImageField(upload_to="type", verbose_name="Фото")),
                ("description", ckeditor.fields.RichTextField(verbose_name="Описание")),
                (
                    "description_detail",
                    ckeditor.fields.RichTextField(verbose_name="Описание Детально"),
                ),
            ],
            options={
                "verbose_name_plural": "Выдающийся Личности Района",
            },
        ),
        migrations.AddField(
            model_name="typeinformation",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="typeinformation",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="type", verbose_name="Фото"
            ),
        ),
        migrations.AddField(
            model_name="typeinformation",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка"),
        ),
        migrations.AddField(
            model_name="typeinformation",
            name="person",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="districts",
                to="passport.person",
                verbose_name="Выдающиеся личности",
            ),
        ),
    ]
