# Generated by Django 4.2.7 on 2025-02-17 13:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0004_person_typeinformation_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="description_detail_ky",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание Детально"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="description_detail_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание Детально"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="description_ky",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="person",
            name="description_ru",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="person",
            name="title_ky",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Тип Информаций"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="title_ru",
            field=models.CharField(
                max_length=155, null=True, verbose_name="Тип Информаций"
            ),
        ),
        migrations.AddField(
            model_name="typeinformation",
            name="description_ky",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="typeinformation",
            name="description_ru",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="typeinformation",
            name="link_ky",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка"),
        ),
        migrations.AddField(
            model_name="typeinformation",
            name="link_ru",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка"),
        ),
    ]
