# Generated by Django 4.2.7 on 2025-02-17 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0005_person_description_detail_ky_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="typeinformation",
            name="link_ky",
        ),
        migrations.RemoveField(
            model_name="typeinformation",
            name="link_ru",
        ),
    ]
