# Generated by Django 4.2.7 on 2025-02-18 10:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0006_remove_typeinformation_link_ky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalinformation',
            options={'verbose_name': 'Жалпы маалымат', 'verbose_name_plural': 'Жалпы маалымат'},
        ),
        migrations.AlterModelOptions(
            name='generalinformationimage',
            options={'verbose_name': 'Сүрөт', 'verbose_name_plural': 'Сүрөттөр'},
        ),
        migrations.AlterModelOptions(
            name='headpersonality',
            options={'verbose_name': 'Атактуу адамдар', 'verbose_name_plural': 'Атактуу адамдар'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Тарых', 'verbose_name_plural': 'Тарыхтар'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Айылдык аймактар', 'verbose_name_plural': 'Айылдык аймактар'},
        ),
        migrations.AlterModelOptions(
            name='infoobject',
            options={'verbose_name': 'Сүрөт', 'verbose_name_plural': 'Маалымат сүрөттөрү'},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карталар'},
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'verbose_name': 'Паспорт району', 'verbose_name_plural': 'Паспорттор райондор'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Атактуу адамдар', 'verbose_name_plural': 'Атактуу адамдар'},
        ),
        migrations.AlterModelOptions(
            name='personality',
            options={'verbose_name': 'Атактуу адам', 'verbose_name_plural': 'Атактуу адамдар'},
        ),
        migrations.AlterModelOptions(
            name='typeinformation',
            options={'verbose_name': 'Маалымат түрү', 'verbose_name_plural': 'Маалымат түрлөрү'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансиялар'},
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Жалпы маалымат сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Жалпы маалымат сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Жалпы маалымат сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='title',
            field=models.CharField(max_length=135, verbose_name='Жалпы маалымат аталышы'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='title_ky',
            field=models.CharField(max_length=135, null=True, verbose_name='Жалпы маалымат аталышы'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='title_ru',
            field=models.CharField(max_length=135, null=True, verbose_name='Жалпы маалымат аталышы'),
        ),
        migrations.AlterField(
            model_name='generalinformationimage',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='headpersonality',
            name='image_personality',
            field=models.ImageField(upload_to='personalities/', verbose_name='Атактуулар сүрөтү'),
        ),
        migrations.AlterField(
            model_name='headpersonality',
            name='title_personality',
            field=models.CharField(max_length=100, verbose_name='Атактуулар аталышы'),
        ),
        migrations.AlterField(
            model_name='headpersonality',
            name='title_personality_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Атактуулар аталышы'),
        ),
        migrations.AlterField(
            model_name='headpersonality',
            name='title_personality_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Атактуулар аталышы'),
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Тарых сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='history',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Тарых сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='history',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Тарых сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(upload_to='history_images/', verbose_name='Тарых сүрөтү'),
        ),
        migrations.AlterField(
            model_name='history',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Тарых аталышы'),
        ),
        migrations.AlterField(
            model_name='history',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Тарых аталышы'),
        ),
        migrations.AlterField(
            model_name='history',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Тарых аталышы'),
        ),
        migrations.AlterField(
            model_name='info',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='info',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='info',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.TextField(verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title_ky',
            field=models.TextField(null=True, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='infoobject',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.info', verbose_name='Маалымат'),
        ),
        migrations.AlterField(
            model_name='map',
            name='link',
            field=models.URLField(verbose_name='Шилтеме'),
        ),
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.TextField(verbose_name='Карта аталышы'),
        ),
        migrations.AlterField(
            model_name='map',
            name='title_ky',
            field=models.TextField(null=True, verbose_name='Карта аталышы'),
        ),
        migrations.AlterField(
            model_name='map',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='Карта аталышы'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Паспорт району сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Паспорт району сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Паспорт району сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='image',
            field=models.ImageField(upload_to='passport_images/', verbose_name='Паспорт району сүрөтү'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Паспорт району аталышы'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Паспорт району аталышы'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Паспорт району аталышы'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description_detail',
            field=ckeditor.fields.RichTextField(verbose_name='Толук сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description_detail_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Толук сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description_detail_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Толук сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(upload_to='type', verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Маалымат түрү'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title_ky',
            field=models.CharField(max_length=155, null=True, verbose_name='Маалымат түрү'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Маалымат түрү'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='all_description_person',
            field=ckeditor.fields.RichTextField(verbose_name='Адамдын толук сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='all_description_person_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Адамдын толук сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='all_description_person_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Адамдын толук сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='description_person',
            field=models.TextField(verbose_name='Адамдын сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='description_person_ky',
            field=models.TextField(null=True, verbose_name='Адамдын сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='description_person_ru',
            field=models.TextField(null=True, verbose_name='Адамдын сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='image_person',
            field=models.ImageField(upload_to='personalities/', verbose_name='Адамдын сүрөтү'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='name_person',
            field=models.CharField(max_length=100, verbose_name='Адамдын аты'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='name_person_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Адамдын аты'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='name_person_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Адамдын аты'),
        ),
        migrations.AlterField(
            model_name='typeinformation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='typeinformation',
            name='description_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='typeinformation',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='typeinformation',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='type', verbose_name='Сүрөт'),
        ),
        migrations.AlterField(
            model_name='typeinformation',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Шилтеме'),
        ),
        migrations.AlterField(
            model_name='typeinformation',
            name='person',
            field=models.ManyToManyField(blank=True, null=True, related_name='districts', to='passport.person', verbose_name='Атактуу адамдар'),
        ),
        migrations.AlterField(
            model_name='typeinformation',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Маалымат түрү'),
        ),
        migrations.AlterField(
            model_name='typeinformation',
            name='title_ky',
            field=models.CharField(max_length=155, null=True, verbose_name='Маалымат түрү'),
        ),
        migrations.AlterField(
            model_name='typeinformation',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Маалымат түрү'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Вакансия сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Вакансия сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Вакансия сүрөттөлүшү'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.TextField(verbose_name='Вакансия аталышы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title_ky',
            field=models.TextField(null=True, verbose_name='Вакансия аталышы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='Вакансия аталышы'),
        ),
    ]
