# Generated by Django 4.2.7 on 2025-02-18 14:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0007_alter_generalinformation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='description_detail',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Вакансия сүрөттөлүшү толук маалымат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_detail_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Вакансия сүрөттөлүшү толук маалымат'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_detail_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Вакансия сүрөттөлүшү толук маалымат'),
        ),
    ]
